package rw.blcp.backend.workflow.config;

public enum EActionType {
    INVALID_STATE_TRANSITION_VALIDATION,
    APPLICANT_OWNERSHIP_VALIDATION,
    OFFICER_LEVEL_VALIDATION,
    REVIEWER_CONFLICT_CHECK,
    RECORD_OFFICER_REVIEW,
    NOTIFICATION
}
