package rw.blcp.backend.workflow.enums;

public enum EActionType {
    APPLICANT_OWNERSHIP_VALIDATION,
    OFFICER_LEVEL_VALIDATION,
    DUPLICATE_REVIEWER_VALIDATION,
    RECORD_OFFICER_REVIEW,
    NOTIFICATION
}
