package rw.blcp.backend.core.workflow.enums;

public enum EActionType {
  SET_APPLICATION_ATTACHMENTS,
  APPLICANT_OWNERSHIP_VALIDATION,
  OFFICER_LEVEL_VALIDATION,
  DUPLICATE_REVIEWER_VALIDATION,
  RECORD_OFFICER_REVIEW,
  RESUBMIT_DOCUMENTS,
  NOTIFICATION
}
