package rw.blcp.backend.core.application.enums;

public enum EPreferenceKey {
  LEVEL1_OFFICER_ID,
  LEVEL2_OFFICER_ID,
  LEVEL1_OFFICER_COMMENT,
  LEVEL2_OFFICER_COMMENT,
  REQUEST_FOR_ACTION_OFFICER_ID,
  REQUEST_FOR_ACTION_OFFICER_COMMENT
}
